# Generated by Django 3.1.4 on 2021-02-14 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Server name')),
                ('ip', models.GenericIPAddressField(verbose_name='Ip address')),
                ('user_root', models.CharField(max_length=32, null=True, verbose_name='Name of root user')),
                ('user_single', models.CharField(max_length=32, null=True, verbose_name='Name of working user')),
                ('password_root', models.CharField(max_length=32)),
                ('password_single', models.CharField(blank=True, max_length=32)),
                ('ssh_key', models.BooleanField(verbose_name='Connect via ssh key')),
                ('log', models.TextField(blank=True, default=None, null=True)),
                ('config', models.TextField(blank=True, default=None, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panel.package')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.server')),
            ],
        ),
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.SmallIntegerField()),
                ('ram_usage', models.IntegerField()),
                ('ram_available', models.IntegerField()),
                ('hdd_usage', models.IntegerField()),
                ('hdd_available', models.IntegerField()),
                ('online', models.IntegerField(default=0)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.server')),
            ],
            options={
                'verbose_name_plural': 'Server status',
            },
        ),
        migrations.CreateModel(
            name='MPackage',
            fields=[
                ('package_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='panel.package')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=32)),
                ('master', models.FileField(null=True, upload_to='packages')),
            ],
            bases=('panel.package',),
        ),
        migrations.CreateModel(
            name='SRPackage',
            fields=[
                ('package_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='panel.package')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=32)),
                ('spawner', models.FileField(null=True, upload_to='packages')),
                ('room', models.FileField(null=True, upload_to='packages')),
            ],
            bases=('panel.package',),
        ),
        migrations.CreateModel(
            name='SubServerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.SmallIntegerField()),
                ('online', models.SmallIntegerField()),
                ('max_online', models.SmallIntegerField()),
                ('server_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.serverstatus')),
            ],
        ),
    ]
