# Generated by Django 3.1.2 on 2020-10-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Server name description')),
                ('ip', models.GenericIPAddressField()),
                ('user_root', models.CharField(max_length=32, verbose_name='Name of root user')),
                ('user_single', models.CharField(max_length=32, verbose_name='Name of working user')),
                ('password_root', models.CharField(max_length=32)),
                ('password_single', models.CharField(max_length=32)),
            ],
        ),
    ]
