# Generated by Django 3.1.4 on 2021-02-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_delete_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='hdd_available',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='hdd_usage',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='ram_available',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='ram_usage',
            field=models.BigIntegerField(),
        ),
    ]
