# Generated by Django 3.1.4 on 2020-12-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20201205_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.SmallIntegerField()),
                ('ram_usage', models.IntegerField()),
                ('ram_available', models.IntegerField()),
                ('hdd_usage', models.IntegerField()),
                ('hdd_available', models.IntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.server')),
            ],
        ),
    ]
