# Generated by Django 3.1.4 on 2020-12-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_serverstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverstatus',
            options={'verbose_name_plural': 'Server status'},
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_key',
            field=models.BooleanField(default=False, verbose_name='Connect via ssh key or password'),
            preserve_default=False,
        ),
    ]
