# Generated by Django 3.1.4 on 2020-12-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20201219_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
