# Generated by Django 3.1.4 on 2020-12-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_auto_20201225_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='package',
            name='size',
        ),
        migrations.AddField(
            model_name='package',
            name='master',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='package',
            name='room',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='package',
            name='spawner',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
