# Generated by Django 3.1.4 on 2021-02-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20210217_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online',
            name='ip',
        ),
        migrations.AlterField(
            model_name='online',
            name='max_online',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='online',
            name='port',
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
