# Generated by Django 3.1.4 on 2020-12-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20201228_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=32)),
                ('master', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SRPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=32)),
                ('spawner', models.FileField(null=True, upload_to='')),
                ('room', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
