# Generated by Django 3.1.4 on 2021-03-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_auto_20210217_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='condition',
            field=models.CharField(choices=[('IN', 'Устаналивается'), ('ST', 'Запускается'), ('RN', 'Запущен'), ('PS', 'Останавливается'), ('SP', 'Остановлен'), ('TR', 'Удаляется')], default='RN', max_length=2),
        ),
    ]
