# Generated by Django 3.1.4 on 2020-12-29 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_auto_20201228_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='m_package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='panel.mpackage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='sr_package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='panel.srpackage'),
            preserve_default=False,
        ),
    ]
