# Generated by Django 3.1.4 on 2021-03-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_status_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='cpu_usage',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='hdd_available',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='hdd_usage',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='ram_available',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='ram_usage',
            field=models.BigIntegerField(null=True),
        ),
    ]
