# Generated by Django 3.1.4 on 2020-12-30 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_auto_20201229_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='m_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='panel.mpackage'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sr_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='panel.srpackage'),
        ),
    ]
