# Generated by Django 3.1.4 on 2021-03-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_auto_20210301_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='condition',
            field=models.CharField(choices=[('IN', 'Устаналивается'), ('ST', 'Запускается'), ('RN', 'Запущен'), ('PS', 'Останавливается'), ('SP', 'Остановлен'), ('TR', 'Удаляется'), ('DL', 'Удалён')], default='RN', max_length=2),
        ),
    ]
