# Generated by Django 3.1.4 on 2021-01-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_auto_20201230_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='config',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mpackage',
            name='master',
            field=models.FileField(null=True, upload_to='packages'),
        ),
        migrations.AlterField(
            model_name='srpackage',
            name='room',
            field=models.FileField(null=True, upload_to='packages'),
        ),
        migrations.AlterField(
            model_name='srpackage',
            name='spawner',
            field=models.FileField(null=True, upload_to='packages'),
        ),
    ]
