# Generated by Django 3.1.4 on 2021-01-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_auto_20210126_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverstatus',
            name='online',
            field=models.IntegerField(default=0),
        ),
    ]
