# Generated by Django 3.1.4 on 2021-01-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_serverstatus_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='online',
            field=models.IntegerField(),
        ),
    ]
