# Generated by Django 3.1.4 on 2021-03-02 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_server_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='pid',
        ),
    ]
