# Generated by Django 3.1.4 on 2021-01-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_auto_20210129_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='online',
            field=models.IntegerField(default=0),
        ),
    ]
