# Generated by Django 3.1.4 on 2021-03-08 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_remove_server_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dedic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='Dedic name')),
                ('ip', models.GenericIPAddressField(verbose_name='Ip address')),
                ('user_root', models.CharField(max_length=32, null=True, verbose_name='Name of root user')),
                ('user_single', models.CharField(max_length=32, null=True, verbose_name='Name of working user')),
                ('password_root', models.CharField(max_length=32)),
                ('password_single', models.CharField(blank=True, max_length=32)),
                ('ssh_key', models.BooleanField(verbose_name='Connect via ssh key')),
                ('log', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='server',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='server',
            name='password_root',
        ),
        migrations.RemoveField(
            model_name='server',
            name='password_single',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_key',
        ),
        migrations.RemoveField(
            model_name='server',
            name='user_root',
        ),
        migrations.RemoveField(
            model_name='server',
            name='user_single',
        ),
        migrations.AddField(
            model_name='server',
            name='dedic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='panel.dedic'),
            preserve_default=False,
        ),
    ]
