# Generated by Django 3.1.4 on 2021-03-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_auto_20210308_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='dedic',
            name='condition',
            field=models.BooleanField(default=False),
        ),
    ]
