# Generated by Django 3.1.7 on 2021-04-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_auto_20210321_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpackage',
            name='master',
            field=models.FileField(upload_to='packages'),
        ),
    ]
