# Generated by Django 3.1.7 on 2021-04-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_auto_20210408_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srpackage',
            name='room',
            field=models.FileField(upload_to='packages'),
        ),
        migrations.AlterField(
            model_name='srpackage',
            name='spawner',
            field=models.FileField(upload_to='packages'),
        ),
    ]
