# Generated by Django 3.2.6 on 2021-08-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_auto_20210408_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dedic',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='mpackage',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='srpackage',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='server',
            name='bin_path',
            field=models.CharField(default=1, max_length=128, verbose_name='Binary path'),
            preserve_default=False,
        ),
    ]
