# Generated by Django 3.2.6 on 2021-08-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0021_auto_20210823_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='bin_path',
        ),
        migrations.AddField(
            model_name='mpackage',
            name='bin_path',
            field=models.CharField(default='./Master.x86_64', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='srpackage',
            name='bin_path',
            field=models.CharField(default='./Spawner.x86_64', max_length=128),
            preserve_default=False,
        ),
    ]
