# Generated by Django 3.2.6 on 2021-08-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0023_auto_20210826_1645'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomPackage',
            new_name='CPackage',
        ),
    ]
