# Generated by Django 3.2.6 on 2021-08-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0024_rename_custompackage_cpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpackage',
            name='bin_path',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
