# Generated by Django 3.2.6 on 2021-09-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0025_cpackage_bin_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='hdd_available',
        ),
        migrations.RemoveField(
            model_name='status',
            name='hdd_usage',
        ),
        migrations.RemoveField(
            model_name='status',
            name='ram_available',
        ),
        migrations.RemoveField(
            model_name='status',
            name='ram_usage',
        ),
        migrations.AddField(
            model_name='status',
            name='disk_available',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='disk_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='mem_available',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='mem_total',
            field=models.IntegerField(null=True),
        ),
    ]
