# Generated by Django 3.2.5 on 2021-10-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0027_server_processes'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='watchdog_port',
            field=models.PositiveSmallIntegerField(default=8000),
            preserve_default=False,
        ),
    ]
