name: Project check

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: project check
      run: |
        npm i
        npm run clearCache
        npm run build
        npm run lint
        npm run test:unit
    - name: SFTP Deployer
      uses: sand4rt/ftp-deployer@v1.3
      with:
        sftp: true # optional
        host: ${{ secrets.FTP_HOST }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
        port: 21 # optional, default is: 21
        username: ${{ secrets.FTP_USERNAME }} # FTP username
        password: ${{ secrets.FTP_PASSWORD }} # FTP password
        remote_folder: ${{ secrets.FTP_REMOTE_FOLDER }} # optional, remote path of your FTP server
        local_folder: dist # optional, local path, default is: dist
        cleanup: false # optional, remove existing files inside FTP remote folder
        pasive: true # optional
      env:
        CI: true

  # e2e-chrome:

  #   runs-on: windows-latest

  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Use Node.js 14
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: 14
  #   - name: e2e chrome test
  #     run: |
  #       npm i
  #       npm run test:e2e
  #     env:
  #       BROWSER: chrome
